### ISSUE TITLE
"Cannot read property 'length' of null" in badges service 

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#624]
crashing the badges service:
```
{"0":"2015-09-12T17:32:51.425Z","2":"error","3":"act","4":"cd-badges","5":"OUT","7":"cmd:addBadgeToProfile,role:cd-badges","8":17,"9":"{role:cd-badges,cmd:addBadgeToProfile,profile:{id:66270c7e-6cfa-4349-85cc-c78fb69b7a0a,name:Jai Sawhney,userId:","10":"ENTRY","11":"(oom9
v)","12":"-","13":"seneca: Action cmd:addBadgeToProfile,role:cd-badges callback threw: Cannot read property 'length' of null.","14":"act_callback","15":"{message:Cannot read property 'length' of null,pattern:cmd:addBadgeToProfile,role:cd-badges,instance:Seneca/0.6","16":"
TypeError: Cannot read property 'length' of null\n    at loadUserParent (/opt/zen/cp-badges-service/lib/send-badge-application.js:44:25)\n    at fn (/opt/zen/cp-badges-service/node_modules/async/lib/async.js:752:34)\n    at /opt/zen/cp-badges-service/node_modules/async/li
b/async.js:1252:16\n    at /opt/zen/cp-badges-service/node_modules/async/lib/async.js:697:43\n    at /opt/zen/cp-badges-service/node_modules/async/lib/async.js:1248:30\n    at Seneca.<anonymous> (/opt/zen/cp-badges-service/lib/send-badge-application.js:37:16)\n    at act_
done (/opt/zen/cp-badges-service/node_modules/seneca/seneca.js:1663:16)\n    at Seneca.<anonymous> (/opt/zen/cp-badges-service/node_modules/seneca/node_modules/gate-executor/gate-executor.js:127:20)\n    at act_done (/opt/zen/cp-badges-service/node_modules/seneca/seneca.j
s:1663:16)\n    at Seneca.<anonymous> (/opt/zen/cp-badges-service/node_modules/seneca/node_modules/gate-executor/gate-executor.js:127:20)"}
```

**Comment by ckiss** [comment]
fixed
