### ISSUE TITLE
'Avatar upload: file must be an image' - shouldn't be a fatal error

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#685]
```

Message: seneca: Action cmd:change_avatar,role:cd-profiles failed: Avatar upload: file must be an image..

Code: act_execute

Details: { id: 'pr1ujez3y5td/htmn4lxo0pmb',
  gate: false,
  ungate: true,
  desc: 'cmd:change_avatar,role:cd-profiles',
  plugin: { name: 'cd-profiles', tag: '-' },
  time: { start: 1442974267482, end: 1442974267482 },
  'orig$': {},
  'message$': 'Avatar upload: file must be an image.',
  message: 'Avatar upload: file must be an image.',
  pattern: 'cmd:change_avatar,role:cd-profiles',
  instance: 'Seneca/0.6.4/zqaka0t3cco5/1442911846944/23486/-' }

Stack:
    at Object.handle_response (/opt/zen/cp-zen-platform/node_modules/seneca-transport/lib/transport-utils.js:86:15)
    at /opt/zen/cp-zen-platform/node_modules/seneca-transport/transport.js:569:16
    at done (/opt/zen/cp-zen-platform/node_modules/needle/lib/needle.js:355:7)
    at PassThrough.<anonymous> (/opt/zen/cp-zen-platform/node_modules/needle/lib/needle.js:523:9)
    at PassThrough.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at wrapped (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at wrapped (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at process._tickDomainCallback (node.js:492:13)
    at process.wrappedFunction (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:262:51)
```

**Comment by ckiss** [comment]
this should be fixed now. I'll deploy the fixes to production
