### ISSUE TITLE
Salesforce error

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#731]
This came into the logs last night

Message: seneca: Action cmd:get_account,role:cd-salesforce failed: [TIMEOUT].

Details: 
  desc: 'cmd:get_account,role:cd-salesforce',
  plugin: { name: 'cd-salesforce', tag: '-' },
  time: { start: 1444343752372, end: 1444343763484 },
  'orig$': { timeout: true },
  'message$': '[TIMEOUT]',
  message: '[TIMEOUT]',
  pattern: 'cmd:get_account,role:cd-salesforce',

Stack: 
    at Object.handle_response (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:86:15)
    at /opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/transport.js:569:16
    at done (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:355:7)
    at PassThrough.<anonymous> (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:523:9)
    at PassThrough.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

Instance: Seneca/0.6.4/6upvsbmhkam6/1444343654795/29455/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/opt/zen/cp-dojos-service/node_modules/seneca/seneca.js:1637:29)

When: 2015-10-08T22:36:03.490Z

SENECA TERMINATED at 2015-10-08T22:36:03.494Z. See above for error report.

**Comment by DanielBrierton** [comment]
Salesforce integration has been stopped, closing
