### ISSUE TITLE
Multiple salesforce validation errors

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#762]
from the logs today:

```
{"0":"2015-09-21T19:44:12.950Z","2":"error","3":"act","4":"cd-salesforce","5":"OUT","7":"cmd:save_account,role:cd-salesforce","8":3819,"9":"{userId:c43be48f-318e-47c4-9e30-5cd39ed06fb7,account:{PlatformId__c:c43be48f-318e-47c4-9e30-5cd39ed06fb7,Email_","10":"ENTRY","11":"(9a6hy)","12":"-","13":"seneca: Action cmd:save,role:entity failed: Billing City: data value too large: Giugliano in Campania, Metropolitan City of Naples (max length=40).","14":"act_execute","15":"{id:8421lu2hyw55/wqh83k860054,gate:false,ungate:true,desc:cmd:save,role:entity,plugin:{name:salesforce-store,ta","16":"STRING_TOO_LONG: Billing City: data value too large: Giugliano in Campania, Metropolitan City of Naples (max length=40)\n    at HttpApi.getError (/opt/zen/cp-salesforce-service/node_modules/jsforce/lib/http-api.js:238:13)\n    at /opt/zen/cp-salesforce-service/node_modules/jsforce/lib/http-api.js:83:22\n    at _fulfilled (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:834:54)\n    at self.promiseDispatch.done (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:863:30)\n    at Promise.promise.promiseDispatch (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:796:13)\n    at /opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:604:44\n    at runSingle (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:137:13)\n    at flush (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:125:13)\n    at wrapped (/opt/zen/cp-salesforce-service/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)\n    at process._tickCallback (node.js:448:13)"}
{"0":"2015-09-28T05:19:29.590Z","2":"error","3":"act","4":"salesforce-store/ARQ","5":"OUT","7":"cmd:save,role:entity","8":1156,"9":"{cmd:save,role:entity,ent:{PlatformId__c:e8c47593-edca-48c0-b94d-ff647f99102f,PlatformURL__c:https://zen.coderd","10":"ENTRY","11":"(6jez3)","12":"-","13":"seneca: Action cmd:save,role:entity failed: Email: invalid email address: coderdojosiret@coderdojo.","14":"act_execute","15":"{id:ar57keyb7xq0/gt7ibcciuvud,gate:false,ungate:true,desc:cmd:save,role:entity,plugin:{name:salesforce-store,ta","16":"INVALID_EMAIL_ADDRESS: Email: invalid email address: coderdojosiret@coderdojo\n    at HttpApi.getError (/opt/zen/cp-salesforce-service/node_modules/jsforce/lib/http-api.js:238:13)\n    at /opt/zen/cp-salesforce-service/node_modules/jsforce/lib/http-api.js:83:22\n    at _fulfilled (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:834:54)\n    at self.promiseDispatch.done (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:863:30)\n    at Promise.promise.promiseDispatch (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:796:13)\n    at /opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:604:44\n    at runSingle (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:137:13)\n    at flush (/opt/zen/cp-salesforce-service/node_modules/jsforce/node_modules/q/q.js:125:13)\n    at wrapped (/opt/zen/cp-salesforce-service/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)\n    at process._tickCallback (node.js:448:13)"}
```

**Comment by tangentfairy** [comment]
From the logs today:
```
Seneca Fatal Error
==================

Message: seneca: Action cmd:save,role:entity failed: City: data value too large: Monte San Pietro, Metropolitan City of Bologna (max length=40).

Code: act_execute

Details: { id: '89gl2s7d4xtl/toa9xqym71gd',
  gate: false,
  ungate: true,
  desc: 'cmd:save,role:entity',
  plugin: { name: 'salesforce-store', tag: 'IOA' },
  time: { start: 1448961151390, end: 1448961152276 },
  'orig$': 
   { name: 'STRING_TOO_LONG',
     errorCode: 'STRING_TOO_LONG',
     fields: [ 'City' ] },
  'message$': 'City: data value too large: Monte San Pietro, Metropolitan City of Bologna (max length=40)',
  message: 'City: data value too large: Monte San Pietro, Metropolitan City of Bologna (max length=40)',
  pattern: 'cmd:save,role:entity',
  instance: 'Seneca/0.7.2/pkyz8vwovs6a/1448020605110/15859/-' }
```

**Comment by Wardormeur** [comment]
Do you have a link to the structure definition on salesforce side? (size, format, etc)

**Comment by DanielBrierton** [comment]
Salesforce integration has been stopped, closing
