### ISSUE TITLE
 Cannot read property 'startTime' of undefined

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#765]
```
2015-10-20T13:06:02.195Z f9hl5u755srk/1445255501185/26975/- ERROR       act     postgresql-store/NQS    OUT             cmd:list,role:entity    1       {qent:{},q:{dojoId:4aa27414-baa9-451f-a250-5bc3fb091520,status:published},cmd:list,role:entity,ent:{},name:even ENTRY   (aze3c) -       seneca: Action cmd:list,role:entity callback threw: Cannot read property 'startTime' of undefined.      act_callback    {message:Cannot read property 'startTime' of undefined,pattern:cmd:list,role:entity,instance:Seneca/0.6.4/f9hl5 TypeError: Cannot read property 'startTime' of undefined
    at /opt/zen/cp-events-service/lib/search-events.js:23:64
    at arrayEach (/opt/zen/cp-events-service/node_modules/lodash/index.js:1367:13)
    at Function.<anonymous> (/opt/zen/cp-events-service/node_modules/lodash/index.js:3413:13)
    at Seneca.<anonymous> (/opt/zen/cp-events-service/lib/search-events.js:20:9)
    at act_done (/opt/zen/cp-events-service/node_modules/seneca/seneca.js:1663:16)
    at /opt/zen/cp-events-service/node_modules/seneca/node_modules/gate-executor/gate-executor.js:127:20
    at /opt/zen/cp-events-service/node_modules/seneca-postgresql-store/lib/postgresql-store.js:249:11
    at null.<anonymous> (/opt/zen/cp-events-service/node_modules/seneca-postgresql-store/lib/postgresql-store.js:145:11)
    at nrWrappedHandler (/opt/zen/cp-events-service/node_modules/newrelic/lib/transaction/tracer/index.js:377:19)
    at wrapped (/opt/zen/cp-events-service/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
```

**Comment by tangentfairy** [comment]
There was another event in the db with an empty start time last week, I removed it. There are still two other events in the db with no dates (created on 8th Oct and 14th Oct, so both recent). It's not supposed to be possible to enter an event without a date.

**Comment by tangentfairy** [comment]
This has not appeared since, so I'm going to close this issue.
