### ISSUE TITLE
 Property 'code' of object Error

### ISSUE THREAD

**Issue by dberesford** [CoderDojo/community-platform#766]
```
2015-10-20T18:26:26.676Z 11ldl14ibt8x/1445358651969/29212/- ERROR       act     remote$         OUT             cmd:*,role:cd-profiles  120003  {cmd:user_profile_data,role:cd-profiles,zenHostname:zen.coderdojo.com,locality:en_US,query:{userId:1464454a-5dc ENTRY   CLIENT  -       seneca: Action cmd:*,role:cd-profiles callback threw: Property 'code' of object Error: seneca: Action cmd:*,role:cd-profiles failed: [TIMEOUT]. is not a function.      act_callback    {message:Property 'code' of object Error: seneca: Action cmd:*,role:cd-profiles failed: [TIMEOUT]. is not a fun TypeError: Property 'code' of object Error: seneca: Action cmd:*,role:cd-profiles failed: [TIMEOUT]. is not a function
    at Seneca.<anonymous> (/opt/zen/cp-zen-platform/lib/handlers.js:37:34)
    at act_done (/opt/zen/cp-zen-platform/node_modules/seneca/seneca.js:1667:16)
    at null.<anonymous> (/opt/zen/cp-zen-platform/node_modules/seneca/node_modules/gate-executor/gate-executor.js:100:11)
    at wrappedCallback (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:338:23)
    at wrapped (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at wrappedCallback (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:429:66)
    at wrapped [as _onTimeout] (/opt/zen/cp-zen-platform/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

Something wrong with passing an Error object into Hapi reply: https://github.com/CoderDojo/cp-zen-platform/blob/master/lib/handlers.js#L36-L37

**Comment by ckiss** [comment]
@tangentfairy @dberesford this is the same with #745

**Comment by tangentfairy** [comment]
Deployed :star2:
