### ISSUE TITLE
Awarding badge crashes profile

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#795]
I have reproduced this both on live and locally.

- Sign up as a new O13 ninja
- Join a Dojo
- Log in as the champion now and award O13 ninja a badge
- Log back in as the O13 ninja and accept the badge
- System crashes when I try to view my dojos or profile (as the ninja)

I get timeout error on cp-zen-platform-stderr.log: 
```
{ [Error: seneca: Action cmd:*,role:user failed: [TIMEOUT].]
  timeout: true,
  eraro: true,
  orig: 
   { [Error: gate-executor: [TIMEOUT]]
     timeout: true,
     eraro: true,
     orig: { [Error: [TIMEOUT]] timeout: true },
     code: 'action-timeout',
     'gate-executor': true,
     package: 'gate-executor',
     msg: 'gate-executor: [TIMEOUT]',
     details: 
      { id: '7v5y22h0tl8l/6issemymufz5',
        gate: false,
        ungate: false,
        desc: 'cmd:*,role:user',
        cb: [Function],
        plugin: [Object],
        fn: [Function],
        time: [Object],
        'orig$': [Object],
        'message$': '[TIMEOUT]' },
     callpoint: 'at null.<anonymous> (/opt/zen/cp-zen-platform/node_modules/seneca/node_modules/gate-executor/gate-executor.js:95:21)' },
  code: 'act_execute',
  'gate-executor': true,
  package: 'seneca',
  msg: 'seneca: Action cmd:*,role:user failed: [TIMEOUT].',
  details: 
   { id: '7v5y22h0tl8l/6issemymufz5',
     gate: false,
     ungate: false,
     desc: 'cmd:*,role:user',
     cb: [Function],
     plugin: { name: 'remote$', tag: undefined },
     fn: [Function],
     time: { start: 1447245931547, end: 1447246051547 },
     'orig$': { [Error: [TIMEOUT]] timeout: true },
     'message$': '[TIMEOUT]',
     message: '[TIMEOUT]',
     pattern: 'cmd:*,role:user',
     instance: 'Seneca/0.7.1/q1cu4rj860o0/1447172475702/1317/-' },
  callpoint: 'at null.<anonymous> (/opt/zen/cp-zen-platform/node_modules/seneca/node_modules/gate-executor/gate-executor.js:95:21)',
  seneca: true }

```

**Comment by ckiss** [comment]
@tangentfairy this seems fixed by the changes made here:
https://github.com/CoderDojo/cp-zen-platform/pull/749 & https://github.com/CoderDojo/cp-users-service/pull/171

**Comment by tangentfairy** [comment]
Working with those changes

**Comment by tangentfairy** [comment]
Deployed!
