### ISSUE TITLE
Cannot edit profile

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#813]
Since yesterdays deployment you cannot edit a profile

```
Seneca Fatal Error
==================

Message: seneca: entity/error

Code: entity/error

Details: { code: 'entity/error', store: 'postgresql-store', plugin: {} }

Stack: 
    at errormaker (/opt/zen/cp-users-service/node_modules/seneca/node_modules/eraro/eraro.js:94:15)
    at Seneca.fail (/opt/zen/cp-users-service/node_modules/seneca/seneca.js:2456:21)
    at error (/opt/zen/cp-users-service/node_modules/seneca-postgresql-store/lib/postgresql-store.js:67:14)
    at /opt/zen/cp-users-service/node_modules/seneca-postgresql-store/lib/postgresql-store.js:173:16
    at null.callback (/opt/zen/cp-users-service/node_modules/seneca-postgresql-store/lib/postgresql-store.js:145:11)
    at Query.handleError (/opt/zen/cp-users-service/node_modules/pg/lib/query.js:97:17)
    at null.<anonymous> (/opt/zen/cp-users-service/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/opt/zen/cp-users-service/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)

Instance: Seneca/0.7.2/gqynt2rr3xrd/1448439105943/25532/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/opt/zen/cp-users-service/node_modules/seneca/seneca.js:1529:29)
```

**Comment by tangentfairy** [comment]
Fixed in https://github.com/CoderDojo/cp-zen-platform/pull/753
