### ISSUE TITLE
Error in dojos service about roles

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#887]
This came into the logs late last night 

```
Message: seneca: Action cmd:update,role:cd-dojos failed: Cannot read property 'roles' of undefined.

Code: act_execute

Details: { id: 'ceu1rdsg6a80/2fsoygrilys2',
  gate: false,
  ungate: true,
  desc: 'cmd:update,role:cd-dojos',
  cb: [Function],
  plugin: { name: 'cd-dojos', tag: '-' },
  fn: [Function],
  time: { start: 1453329689451 },
  'orig$': [TypeError: Cannot read property 'roles' of undefined],
  'message$': 'Cannot read property \'roles\' of undefined',
  message: 'Cannot read property \'roles\' of undefined',
  pattern: 'cmd:update,role:cd-dojos',
  instance: 'Seneca/0.7.2/445m07l55hc4/1453315315675/2203/-' }

Stack: 
    at checkUserDojoPermissions (/opt/zen/cp-dojos-service/dojos.js:926:24)
    at /opt/zen/cp-dojos-service/dojos.js:974:7
    at /opt/zen/cp-dojos-service/dojos.js:967:16
    at /opt/zen/cp-dojos-service/dojos.js:948:14
    at Entity.load$ (/opt/zen/cp-dojos-service/node_modules/seneca/lib/entity.js:184:12)
    at checkDojoExists (/opt/zen/cp-dojos-service/dojos.js:946:29)
    at Seneca.<anonymous> (/opt/zen/cp-dojos-service/dojos.js:964:7)
    at Object.execspec.fn (/opt/zen/cp-dojos-service/node_modules/seneca/seneca.js:1608:24)
    at Object.<anonymous> (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/gate-executor/gate-executor.js:108:14)
    at Object.wrapped [as _onImmediate] (/opt/zen/cp-dojos-service/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)


```

**Comment by Wardormeur** [comment]
Didn't happen since january, closing
