### ISSUE TITLE
Salesforce not logging new accounts and leads

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#888]
Found out that part of this is due to a password issue, there is also another error:

```
Seneca Fatal Error
==================

Message: seneca: Action cmd:save,role:entity failed: Record Type ID: this ID value isn't valid for the user: .

Code: act_execute

Details: { id: 'dshi7rvey4nn/zjk1qq9fw0pd',
  gate: false,
  ungate: true,
  desc: 'cmd:save,role:entity',
  plugin: { name: 'salesforce-store', tag: 'EAO' },
  time: { start: 1453310182700, end: 1453310183100 },
  'orig$': 
   { name: 'INVALID_CROSS_REFERENCE_KEY',
     errorCode: 'INVALID_CROSS_REFERENCE_KEY',
     fields: [ 'RecordTypeId' ] },
  'message$': 'Record Type ID: this ID value isn\'t valid for the user: ',
  message: 'Record Type ID: this ID value isn\'t valid for the user: ',
  pattern: 'cmd:save,role:entity',
  instance: 'Seneca/0.7.2/827rphv994sq/1453310100025/1048/-' }

Stack: 
    at Object.handle_response (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/lib/transport-utils.js:86:15)
    at /opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/transport.js:569:16
    at done (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:355:7)
    at PassThrough.<anonymous> (/opt/zen/cp-dojos-service/node_modules/seneca/node_modules/seneca-transport/node_modules/needle/lib/needle.js:523:9)
    at PassThrough.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by tangentfairy** [comment]
Fixed, issue with account - needs to be a knowledge only user.
