### ISSUE TITLE
Jenkins build failures

### ISSUE THREAD

**Issue by tangentfairy** [CoderDojo/community-platform#910]
Jenkins is failing on CrowdIn errors, due to no API key being found, and also due to syntax errors in messages.po.

It seems that CrowdIn have changed something in their integration to cause this. I'm investigating at the moment.

**Comment by dariocravero** [comment]
@tangentfairy could you point me to jenkins' output? thanks! :)

**Comment by tangentfairy** [comment]
@dariocravero I do believe that Dean has someone who is going to look into this, but here it is anyway in case you have a bright idea:

```
[32m23 02 2016 14:25:18.355:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: [39mConnected on socket /#VwkFyCv8sP9WqpmNAAAA with id 22076910
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  Error: Cannot find module '/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/test/review-champion-application-spec.js'
  at /tmp/a5da887112fa69bbafec76e04a204426.browserify:1


PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  Error: Cannot find module '/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/test/stats-spec.js'
  at /tmp/a5da887112fa69bbafec76e04a204426.browserify:1


Unhandled rejection Error: Not running
    at Server.close (net.js:1237:11)
    at /var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/node_modules/karma/lib/server.js:342:17
    at tryCatcher (/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/node_modules/karma/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/node_modules/karma/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/node_modules/karma/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/node_modules/karma/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/node_modules/karma/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/node_modules/karma/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/var/lib/jenkins/jobs/cp-zen-platform-codedeploy/workspace/node_modules/karma/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
npm ERR! Test failed.  See above for more details.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by dariocravero** [comment]
Yeah, I'd need more background on this I guess in order to even know where to start looking for that. At a first glance it seems like there might be some missing modules from the browserify bundle but your initial message says that it's related to CrowdIn so I wouldn't really know then...

**Comment by tangentfairy** [comment]
Ah sorry, there are two issues! This one is about CrowdIn :) the issue is that it looks for an API key, and the solution is to add the crowdin.yaml file out of version control and update it on the server with the API key.

Someone internal needs to do this and it is assigned to me. Thanks anyway @dariocravero ! :)

**Comment by Wardormeur** [comment]
Closing as we're gonna move to CircleCI and it's a non-blocking issue anyway ;)
